/* Native UI. All user-controlled content is rendered as text. */
'use strict';
(()=>{
const C=DTA,$=id=>document.getElementById(id),KEY='dream-to-action.operations.personal.v1';
let personal=C.empty(),demo=C.validate(DTA_DEMO),w=personal,backup=false,dirty=false,view='overview',submitEditor=null;
const N=(tag,txt='',attrs={})=>{const n=document.createElement(tag);n.textContent=txt;for(const [k,v] of Object.entries(attrs))n.setAttribute(k,String(v));return n;};
const B=(txt,fn,cls='secondary')=>{const b=N('button',txt,{type:'button',class:cls});b.addEventListener('click',fn);return b;};
const names={ready:'Ready to consider',blocked:'Needs support',review:'Needs review',paused:'Paused / closed',done:'Completed action'};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function say(s){$('status').textContent=s;}
function error(e){$('error').textContent=e.message||String(e);$('error').hidden=false;}
function clearError(){$('error').hidden=true;}
function persist(){if(!backup)return;try{localStorage.setItem(KEY,JSON.stringify(personal));$('backup-status').textContent='Personal workspace backed up in this browser. Unencrypted; export for a separate copy.';}catch(e){$('backup-status').textContent='Browser backup failed. Your current records remain in memory; export now.';error(new Error('Browser backup could not be written. Do not close before exporting.'));}}
function transact(fn){const next=C.clone(w);fn(next);const checked=C.validate(next);w=checked;if(w.mode==='personal')personal=w;else demo=w;dirty=true;clearError();persist();render();say('Record saved in the '+w.mode+' workspace. '+(backup&&w.mode==='personal'?'Check browser backup status below.':'Export to keep it after closing.'));}
function openView(name,focus=false){view=['overview','board','evidence','resources'].includes(name)?name:'overview';for(const n of ['overview','board','evidence','resources'])$('view-'+n).hidden=n!==view;document.querySelectorAll('nav [data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(focus){const h=$('view-'+view).querySelector('h1');h.setAttribute('tabindex','-1');h.focus();}}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view,true)));
document.querySelector('.brand').addEventListener('click',()=>openView('overview',true));
function badge(s){return N('span',names[s],{class:'badge '+s});}
function field(form,name,label,type,value,options,help){const wrap=N('div');const lab=N('label',label,{for:'f-'+name});let el=N(type==='textarea'?'textarea':type==='select'?'select':'input','',{id:'f-'+name,name});if(type==='select')for(const [v,t] of options)el.append(N('option',t,{value:v}));else if(type!=='textarea')el.type=type;el.value=value??'';if(['text','textarea'].includes(type))el.maxLength=4000;if(type==='number'){el.min=0;el.max=1000000;el.step='any';}if(!['due','cost','minutes','need','provider','supportNote','source','dependency'].includes(name))el.required=true;wrap.append(lab,el);if(help){const p=N('p',help,{id:'help-'+name,class:'field-help'});el.setAttribute('aria-describedby',p.id);wrap.append(p);}form.append(wrap);return el;}
function editor(title,help,fields,save){$('editor-title').textContent=title;$('editor-help').textContent=help;$('editor-fields').replaceChildren();$('editor-error').textContent='';for(const f of fields)field($('editor-fields'),...f);submitEditor=save;$('editor').showModal();$('editor-fields').querySelector('input,textarea,select')?.focus();}
$('close-editor').onclick=()=>$('editor').close();
$('editor-form').addEventListener('input',()=>{dirty=true;});
$('editor-form').onsubmit=e=>{e.preventDefault();try{const v=Object.fromEntries(new FormData(e.currentTarget));submitEditor(v);$('editor').close();}catch(err){$('editor-error').textContent=err.message;}};
function note(title,help,fn){editor(title,help,[['note','Your note','textarea','']],v=>transact(n=>fn(n,v.note)));}
const categories=['Work','Learning','Stability','Care','Enterprise','Community','Other'];
function openGoal(g){const fields=[['title','What direction do you choose?','text',g?.title||''],['barrier','What is the actual barrier?','textarea',g?.barrier||''],['success','What observable change would matter?','textarea',g?.success||''],['category','Area of life','select',g?.category||'Other',[...new Set([...categories,g?.category].filter(Boolean))].map(v=>[v,v])]];if(g)fields.push(['state','Your choice about this goal','select',g.state,[['active','Active'],['paused','Paused by choice'],['achieved','Achieved, by my report']]],['reason','Why is this revision needed?','textarea','']);editor(g?'Revise your goal':'Choose a direction','A goal belongs to you. Revising it preserves the previous version and makes unfinished actions require review.',fields,v=>transact(n=>g?C.reviseGoal(n,g.id,v,v.reason):C.addGoal(n,v)));}
function options(){return w.goals.map(g=>[g.id,g.title]);}
function openAction(resource){if(!w.goals.length)return error(new Error('Create a goal first. The action needs a direction you chose.'));editor('Choose a next action','An owner is a proposed role, not an agreement. Blank time and USD estimates mean unknown, not zero.',[
 ['goalId','For which goal?','select',w.goals[0].id,options()],['title','Concrete next action','textarea',resource?.next||''],['owner','Proposed action owner','text','Me'],['due','Target date (no reminder is created)','date',''],['minutes','Estimated minutes (optional)','number',''],['cost','Estimated cost in USD (optional)','number',''],['need','Support or change required (optional)','textarea',resource?'Check eligibility, availability, cost, and access with the actual provider.':''],['provider','Possible support provider (optional)','text',resource?.publisher||''],['support','Support status','select','unknown',C.SUPPORT.map(x=>[x,x.replaceAll('_',' ')])],['supportNote','Basis for support status (required when confirmed)','textarea',resource?'Reference only, checked '+resource.checked+': '+resource.url:''],['dependency','Preceding action (optional)','select','',[['','No predecessor'],...w.actions.filter(a=>a.goalId===w.goals[0].id).map(a=>[a.id,a.title])]]
 ],v=>transact(n=>C.addAction(n,{...v,minutes:v.minutes===''?null:Number(v.minutes),cost:v.cost===''?null:Number(v.cost),dependsOn:v.dependency?[v.dependency]:[]})));
 $('f-goalId').onchange=()=>{const el=$('f-dependency');el.replaceChildren(N('option','No predecessor',{value:''}));for(const a of w.actions.filter(a=>a.goalId===$('f-goalId').value))el.append(N('option',a.title,{value:a.id}));};}
function editAction(a){if(a.dependsOn.length>1)return error(new Error('This imported action has multiple predecessors. Use a new successor action rather than silently dropping dependencies.'));editor('Revise the next action','Keep the old record in history. The goal stays the same; confirming this revision means you reviewed its fit with the current goal.',[['title','Concrete next action','textarea',a.title],['owner','Proposed owner','text',a.owner],['due','Target date (no reminder)','date',a.due],['minutes','Estimated minutes','number',a.minutes],['cost','Estimated cost in USD','number',a.cost],['dependency','Preceding action','select',a.dependsOn[0]||'',[['','No predecessor'],...w.actions.filter(b=>b.goalId===a.goalId&&b.id!==a.id).map(b=>[b.id,b.title])]],['note','Why is this revision needed?','textarea','']],v=>transact(n=>C.reviseAction(n,a.id,{title:v.title,owner:v.owner,due:v.due,minutes:v.minutes===''?null:Number(v.minutes),cost:v.cost===''?null:Number(v.cost),dependsOn:v.dependency?[v.dependency]:[]},v.note)));}
function support(a){editor('Confirm the conditions','A directory listing or an unanswered request is not a commitment. Confirmed support needs a provider and a note.',[['support','Support status','select',a.support,C.SUPPORT.map(x=>[x,x.replaceAll('_',' ')])],['need','Required support','textarea',a.need],['provider','Provider or role','text',a.provider],['supportNote','What establishes this status?','textarea',a.supportNote]],v=>transact(n=>C.updateSupport(n,a.id,v)));}
function evidence(){if(!w.goals.length)return error(new Error('Create a goal before recording an observation.'));editor('Record an observation','Describe what happened, the limits of the observation, and what is still unresolved. No evidence class is independently verified by this app.',[['goalId','Which goal?','select',w.goals[0].id,options()],['outcome','What changed?','select','unknown',[['unknown','Unresolved / not enough evidence'],['improved','Improvement reported'],['no_change','No change observed'],['harm','Harm or unacceptable cost']]],['kind','Basis of the record','select','self_reported',[['self_reported','Self-reported'],['observed','Direct observation, by my report'],['documented','Documented reference, not independently checked']]],['note','Observation and remaining uncertainty','textarea',''],['source','Source reference (required for documented records)','text','']],v=>transact(n=>C.observe(n,v)));}
$('new-goal').onclick=()=>openGoal();$('new-action').onclick=()=>openAction();$('new-observation').onclick=evidence;
function summary(){const m=C.metrics(w);$('metrics').replaceChildren();for(const [value,label,sub] of [[m.active,'Active directions','Goals you chose'],[m.ready,'Actions ready to consider','Conditions recorded, not certified'],[m.blocked+m.review,'Conditions to resolve','Support or review needed'],[m.improved,'Improvement reports','Not verified causal outcomes']]){const c=N('div','',{class:'metric'});c.append(N('span',label,{class:'metric-label'}),N('strong',value),N('small',sub));$('metrics').append(c);}
 const count=w.actions.length;$('status-chart').replaceChildren();for(const s of ['ready','blocked','review','paused','done']){const row=N('div','',{class:'chart-row '+s});const p=N('progress','',{max:Math.max(1,count),value:m[s],'aria-label':names[s]+': '+m[s]+' of '+count});row.append(N('span',s==='ready'?'Ready':s==='blocked'?'Support':s==='review'?'Review':s==='paused'?'Paused':'Completed'),p,N('strong',m[s]));$('status-chart').append(row);}
 $('estimates').replaceChildren(N('p','Estimated work: '+m.minutes+' minutes; '+m.unknownMinutes+' actions have unknown time.'),N('p','Known cost estimates: $'+m.cost.toLocaleString('en-US',{maximumFractionDigits:2})+' USD; '+m.unknownCost+' actions have unknown cost. Estimates are not spending.'),N('p',m.done+' of '+count+' actions recorded complete. This is task throughput, not a measure of life success.'));
 const next=w.actions.filter(a=>!['done','paused'].includes(C.status(w,a))).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).slice(0,4);$('next-actions').replaceChildren();if(!next.length)$('next-actions').append(N('p',w.actions.length?'No active unfinished actions. Choose whether to revise or add another.':'No actions yet. Start with one goal and one practical next step.',{class:'empty'}));next.forEach((a,i)=>{const r=N('div','',{class:'next-row'}),t=N('div');t.append(N('p',a.title),N('p',(a.due||'No target date')+' · '+a.owner,{class:'muted'}));r.append(N('span',String(i+1).padStart(2,'0'),{class:'next-number'}),t,badge(C.status(w,a)));$('next-actions').append(r);});
 flow(m);}
function flow(m){const ns='http://www.w3.org/2000/svg',S=(tag,attrs,txt)=>{const n=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);if(txt!==undefined)n.textContent=txt;return n;};const svg=S('svg',{viewBox:'0 0 700 150',class:'flow-svg',role:'img','aria-labelledby':'flow-title flow-description'});svg.append(S('title',{id:'flow-title'},'Goal, conditions, actions, and observations'),S('desc',{id:'flow-description'},'Counts for the selected '+w.mode+' workspace; exact values are also in the table below.'));
 const values=[['Chosen goals',m.goals],['Support confirmed',w.actions.filter(a=>a.support==='confirmed').length],['Actions complete',m.done],['Observations',m.observations]];values.forEach(([label,value],i)=>{const x=10+i*177;if(i<3)svg.append(S('path',{d:`M ${x+150} 66 H ${x+173} m -6 -4 l 6 4 -6 4`,class:'edge'}));svg.append(S('rect',{x,y:22,width:150,height:91,rx:13,class:'node'}),S('text',{x:x+75,y:61,'text-anchor':'middle',class:'number'},value),S('text',{x:x+75,y:91,'text-anchor':'middle'},label));});
 const table=N('table','',{class:'flow-table'}),head=N('tr'),row=N('tr');values.forEach(([label,value])=>{head.append(N('th',label,{scope:'col'}));row.append(N('td',value));});table.append(head,row);$('flow-chart').replaceChildren(svg,table);}
function goals(){$('goal-grid').replaceChildren();if(!w.goals.length)$('goal-grid').append(N('div','No preset definition of success. Add your first chosen direction, or explore the explicitly fictional demo.',{class:'empty'}));for(const g of w.goals){const as=w.actions.filter(a=>a.goalId===g.id),done=as.filter(a=>a.state==='done').length,c=N('article','',{class:'goal-card'});c.append(N('span',g.category+' · revision '+g.revision,{class:'category'}),N('h3',g.title),N('p','Barrier: '+g.barrier),N('p','Progress would mean: '+g.success),N('p',g.state+' · '+done+'/'+as.length+' actions complete'),N('progress','',{max:Math.max(1,as.length),value:done,'aria-label':g.title+': '+done+' of '+as.length+' actions complete'}),B('Revise goal',()=>openGoal(g)));$('goal-grid').append(c);}
 const selected=$('goal-filter').value;$('goal-filter').replaceChildren(N('option','All goals',{value:''}));for(const g of w.goals)$('goal-filter').append(N('option',g.title,{value:g.id}));$('goal-filter').value=w.goals.some(g=>g.id===selected)?selected:'';}
function board(){const filter=$('goal-filter').value,q=$('action-search').value.toLowerCase();$('board').replaceChildren();for(const state of ['ready','blocked','review','paused','done']){const list=w.actions.filter(a=>C.status(w,a)===state&&(!filter||filter===a.goalId)&&[a.title,a.owner,C.getGoal(w,a.goalId).barrier].join(' ').toLowerCase().includes(q));const lane=N('section','',{class:'lane'}),h=N('h2',names[state]);h.append(N('span',list.length));lane.append(h);if(!list.length)lane.append(N('p','No matching actions.',{class:'muted'}));for(const a of list){const card=N('article','',{class:'action-card'});card.append(N('span',C.getGoal(w,a.goalId).category,{class:'eyebrow'}),N('h3',a.title),N('p',C.getGoal(w,a.goalId).title),N('p','Owner: '+a.owner),N('p','Target: '+(a.due||'Not set')+(a.due&&a.due<today()&&state!=='done'?' · date passed':''),{class:a.due&&a.due<today()&&state!=='done'?'overdue':'muted'}),N('p',C.reason(w,a)),N('p','Support: '+a.support.replaceAll('_',' ')+' · goal revision '+a.revision));if(state!=='done'){card.append(B('Edit action',()=>editAction(a)),B('Support',()=>support(a)));if(state==='ready')card.append(B('Record completion',()=>note('What was completed?','A completed action is not automatically a beneficial outcome.',(n,v)=>C.completeAction(n,a.id,v))));if(state==='review')card.append(B('Review action',()=>note('Does this action still fit?','Check the current goal, consequences, and any harm report before reaffirming this action.',(n,v)=>C.reviewAction(n,a.id,v))));}lane.append(card);}$('board').append(lane);}}
function history(){$('observation-list').replaceChildren();if(!w.observations.length)$('observation-list').append(N('p','No observations recorded. Completing an action does not create one.',{class:'empty'}));for(const o of [...w.observations].reverse()){const c=N('article','',{class:'evidence-card '+o.outcome});c.append(N('span',o.kind.replaceAll('_',' ')+' · '+o.outcome.replaceAll('_',' '),{class:'eyebrow'}),N('h3',C.getGoal(w,o.goalId).title),N('p',o.note),N('p','Source: '+(o.source||'Not supplied'),{class:'muted'}),N('p',o.createdAt+' · goal revision '+o.revision,{class:'muted'}));$('observation-list').append(c);}$('event-list').replaceChildren();for(const e of [...w.events].reverse()){const d=N('details','',{class:'event'});d.append(N('summary',e.type.replaceAll('-',' ')+' · '+e.at),N('pre',e.detail),N('p','Record '+e.entityId,{class:'muted'}));$('event-list').append(d);}if(!w.events.length)$('event-list').append(N('p','History begins when you record something.',{class:'muted'}));$('legacy-panel').hidden=w.legacy===null;}
function resources(){const q=$('resource-search').value.toLowerCase();$('resource-grid').replaceChildren();for(const r of DTA_RESOURCES.filter(r=>[r.title,r.category,r.summary].join(' ').toLowerCase().includes(q))){const c=N('article','',{class:'goal-card'});c.append(N('span',r.category,{class:'category'}),N('h3',r.title),N('p',r.summary),N('p','Confirm: '+r.confirm),N('p',r.publisher+' · checked '+r.checked,{class:'muted'}));const link=N('a','Open official source ↗',{href:r.url,target:'_blank',rel:'noopener noreferrer'});c.append(link,N('br'),B('Draft a next action',()=>openAction(r)));$('resource-grid').append(c);}if(!$('resource-grid').childElementCount)$('resource-grid').append(N('p','No matching reference. No claim is made that other resources do not exist.',{class:'empty'}));}
function render(){$('workspace-mode').textContent=w.mode==='demo'?'Illustrative demo · synthetic data only':'Personal workspace · nothing uploaded';$('mode-notice').textContent=w.mode==='demo'?'DEMONSTRATION ONLY · All goals, actions, costs, dates, and outcomes below are fictional. Your personal workspace is separate.':'PERSONAL WORKSPACE · Your records, your goals. This app does not send messages, apply for services, or decide eligibility.';$('mode-notice').className='notice'+(w.mode==='demo'?' demo-notice':'');$('mode-switch').textContent=w.mode==='demo'?'Return to personal workspace':'Explore illustrative demo';summary();goals();board();history();resources();openView(view);}
$('goal-filter').onchange=board;$('action-search').oninput=board;$('resource-search').oninput=resources;
$('mode-switch').onclick=()=>{w=w.mode==='personal'?demo:personal;clearError();render();say('Switched workspace. Personal and illustrative data are never combined.');};
function download(data,type,name){const url=URL.createObjectURL(new Blob([data],{type})),a=N('a','',{href:url,download:name});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);say('Download requested. Check the saved file; it is not encrypted.');}
$('export-json').onclick=()=>{try{const data=C.validate(w);let json=JSON.stringify(data,null,2);if(new Blob([json]).size>C.MAX_BYTES)json=JSON.stringify(data);download(json,'application/json','dream-to-action-'+w.mode+'.json');}catch(e){error(e);}};
$('export-csv').onclick=()=>download('\uFEFF'+C.csv(w),'text/csv;charset=utf-8','dream-to-action-'+w.mode+'-actions.csv');
$('export-report').onclick=()=>{const lines=['DREAM TO ACTION — '+w.mode.toUpperCase(),'Exported: '+new Date().toISOString(),'Self-reported or illustrative records. No independent verification. Estimates are not actual spending.',''];for(const g of w.goals){lines.push('GOAL: '+g.title,'State: '+g.state+' / revision '+g.revision,'Barrier: '+g.barrier,'Observable change: '+g.success);for(const a of w.actions.filter(a=>a.goalId===g.id))lines.push('ACTION: '+a.title,'Owner: '+a.owner+' / target: '+(a.due||'not set'),'Status: '+C.status(w,a)+' / '+C.reason(w,a),'Support: '+a.need+' / provider: '+a.provider+' / basis: '+a.supportNote,'Estimate: '+(a.cost??'unknown')+' USD / '+(a.minutes??'unknown')+' minutes');for(const o of w.observations.filter(o=>o.goalId===g.id))lines.push('OBSERVATION: '+o.createdAt+' / '+o.kind+' / '+o.outcome+' / revision '+o.revision,o.note,'Source: '+(o.source||'not supplied'));lines.push('');}lines.push('FULL STRUCTURED RECORD (including revisions, events, and retained original source)',JSON.stringify(w,null,2));download(lines.join('\n'),'text/plain;charset=utf-8','dream-to-action-'+w.mode+'-handoff.txt');};
$('export-legacy').onclick=()=>{if(w.legacy)download(JSON.stringify(w.legacy,null,2)+'\n','application/json','dream-to-action-retained-v01.json');};
let importing=false;
$('import-file').onchange=async()=>{const file=$('import-file').files[0];if(!file||importing)return;importing=true;const initial=JSON.stringify(w),original=w;try{if(file.size>C.MAX_BYTES)throw new Error('Maximum import size is 2 MiB.');const candidate=C.importData(await file.text());if(w!==original||JSON.stringify(w)!==initial)throw new Error('Workspace changed while reading. Retry after finishing the current edit.');const target=candidate.mode==='personal'?personal:demo;if((target.goals.length||target.legacy)&&!confirm('Replace the '+candidate.mode+' workspace? Export first. This does not merge records.'))return;if(candidate.mode==='personal')personal=candidate;else demo=candidate;w=candidate;dirty=true;clearError();persist();render();say('Restored '+w.mode+' records. Imported content and timestamps remain unverified.');}catch(e){error(e);}finally{importing=false;$('import-file').value='';}};
$('local-backup').onchange=()=>{if($('local-backup').checked){if(!confirm('Store your personal workspace unencrypted in this browser? Other people using this browser profile may access it.')){$('local-backup').checked=false;return;}backup=true;persist();}else{backup=false;try{localStorage.removeItem(KEY);$('backup-status').textContent='Browser backup removed. Exported files and device traces are not deleted.';$('restore-backup').hidden=true;}catch(e){error(new Error('Could not remove the browser backup. Check browser storage controls.'));}}};
$('restore-backup').onclick=()=>{try{const raw=localStorage.getItem(KEY);if(!raw)throw new Error('No saved browser backup is available.');const candidate=C.importData(raw);if(candidate.mode!=='personal')throw new Error('Browser backup is not a personal workspace.');if(personal.goals.length&&!confirm('Replace personal records from this browser backup? Export first.'))return;personal=candidate;w=personal;backup=true;$('local-backup').checked=true;render();$('backup-status').textContent='Personal browser backup restored. Unencrypted.';say('Browser backup restored. Export for a separate copy.');}catch(e){error(e);}};
$('clear-workspace').onclick=()=>{if(!confirm('Clear the selected '+w.mode+' workspace? Export first. If browser backup is enabled, its personal copy will also be replaced when clearing personal data. Exported files and device traces are not deleted.'))return;w=C.empty(w.mode);if(w.mode==='personal')personal=w;else demo=w;dirty=true;persist();render();say('Selected workspace cleared. Other workspace and exported files remain unchanged.');};
try{if(localStorage.getItem(KEY)){$('restore-backup').hidden=false;$('backup-status').textContent='A previous browser backup exists. Restore it explicitly; it has not been opened.';}}catch(e){$('backup-status').textContent='Browser storage is unavailable. Use JSON export.';}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
render();
})();
