/* Dream to Action operations: pure data rules. No DOM, storage, or network access. */
(function(root,factory){'use strict';if(typeof module==='object'&&module.exports)module.exports=factory();else root.DTA=factory();})(globalThis,()=>{
'use strict';
const SCHEMA='dta-operations/1',MAX_BYTES=2097152;
const SUPPORT=['unknown','requested','confirmed','not_needed','unavailable'];
const OUTCOMES=['unknown','improved','no_change','harm'];
const clone=x=>JSON.parse(JSON.stringify(x));
const now=()=>new Date().toISOString();
let seq=0;
const uid=p=>p+'-'+(globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+(++seq));
function insist(ok,msg){if(!ok)throw new Error(msg);}
function text(v,label,required=false,max=4000){insist(typeof v==='string'&&v.length<=max&&(!required||v.trim()),label+' must be '+(required?'nonempty ':'')+'text (maximum '+max+' code units).');return v;}
function choice(v,values,label){insist(values.includes(v),'Unsupported '+label+'.');return v;}
function keys(o,names,label){insist(o&&typeof o==='object'&&!Array.isArray(o)&&Object.keys(o).length===names.length&&names.every(k=>Object.hasOwn(o,k)),label+' has missing or unknown fields.');}
function date(v,optional=true){if(v===''&&optional)return;insist(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!v.startsWith('0000'),'Invalid date.');const d=new Date(v+'T00:00:00Z');insist(!Number.isNaN(+d)&&d.toISOString().slice(0,10)===v,'Invalid calendar date.');}
function timestamp(v){insist(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString()===v,'Invalid timestamp.');}
function number(v,label){insist(v===null||(typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=1000000),'Invalid '+label+'.');}
function id(v){insist(typeof v==='string'&&/^[a-z][a-z0-9_-]{1,79}$/.test(v),'Invalid identifier.');}
function capacity(w){insist(w.events.length<5000,'History is full. Export before starting another workspace.');}
function event(w,type,entityId,detail){capacity(w);text(detail,'History detail',false,32768);w.events.push({id:uid('e'),type,entityId,at:now(),detail});}
function empty(mode='personal'){choice(mode,['personal','demo'],'workspace mode');return {schema:SCHEMA,mode,createdAt:now(),goals:[],actions:[],observations:[],events:[],legacy:null};}
function goalFields(g){text(g.title,'Goal',true);text(g.barrier,'Barrier',true);text(g.success,'Observable change',true);text(g.category,'Category',true);}
function supportFields(a){SUPPORT.includes(a.support)||choice(a.support,SUPPORT,'support status');for(const k of ['need','provider','supportNote'])text(a[k],k);if(a.support==='confirmed')insist(a.provider.trim()&&a.supportNote.trim(),'Confirmed support needs a provider and a confirmation note.');if(a.support==='not_needed')insist(!a.need.trim(),'A required dependency cannot also be marked not needed.');}
function getGoal(w,g){const found=w.goals.find(x=>x.id===g);insist(found,'Goal reference not found.');return found;}
function getAction(w,a){const found=w.actions.find(x=>x.id===a);insist(found,'Action reference not found.');return found;}
function snapshot(g,at){return {revision:g.revision,title:g.title,barrier:g.barrier,success:g.success,category:g.category,state:g.state,at};}
function addGoal(w,p){goalFields(p);capacity(w);insist(w.goals.length<200,'Limit: 200 goals per workspace.');const g={id:uid('g'),title:p.title,barrier:p.barrier,success:p.success,category:p.category,state:'active',revision:1,createdAt:now(),history:[]};g.history.push(snapshot(g,g.createdAt));w.goals.push(g);event(w,'goal-created',g.id,'Person-chosen goal recorded.');return g;}
function reviseGoal(w,goalId,p,reason){goalFields(p);choice(p.state,['active','paused','achieved'],'goal state');text(reason,'Revision reason',true);capacity(w);const g=getGoal(w,goalId);insist(g.history.length<100,'Goal revision limit reached; export before starting a successor.');const before=snapshot(g,now());for(const k of ['title','barrier','success','category','state'])g[k]=p[k];g.revision++;g.history.push(snapshot(g,now()));event(w,'goal-revised',g.id,JSON.stringify({reason,before,after:g.history.at(-1)}));return g;}
function actionFields(a){text(a.title,'Action',true);text(a.owner,'Owner',true);date(a.due);number(a.minutes,'estimated minutes');number(a.cost,'estimated USD');supportFields(a);insist(Array.isArray(a.dependsOn)&&a.dependsOn.length<=100&&new Set(a.dependsOn).size===a.dependsOn.length,'Invalid action dependencies.');a.dependsOn.forEach(id);}
function addAction(w,p){actionFields(p);capacity(w);insist(w.actions.length<500,'Limit: 500 actions per workspace.');const g=getGoal(w,p.goalId);for(const dep of p.dependsOn)insist(getAction(w,dep).goalId===g.id,'Dependencies must be in the same goal.');const a={id:uid('a'),goalId:g.id,revision:g.revision,title:p.title,owner:p.owner,due:p.due,minutes:p.minutes,cost:p.cost,need:p.need,provider:p.provider,support:p.support,supportNote:p.supportNote,dependsOn:[...p.dependsOn],state:'todo',completion:'',createdAt:now(),reviewedAt:now()};w.actions.push(a);event(w,'action-created',a.id,'Action linked to goal revision '+g.revision+'.');return a;}
function reviseAction(w,actionId,p,note){text(note,'Revision reason',true);capacity(w);const a=getAction(w,actionId);insist(a.state==='todo','Completed actions are historical. Create a new action instead.');const candidate={...a,...p,revision:getGoal(w,a.goalId).revision,reviewedAt:now()};actionFields(candidate);const trial=clone(w);Object.assign(getAction(trial,actionId),candidate);validate(trial);const before=clone(a);Object.assign(a,candidate);event(w,'action-revised',a.id,JSON.stringify({note,before,after:a}));}
function status(w,a){const g=getGoal(w,a.goalId);if(a.state==='done')return 'done';if(g.state!=='active')return 'paused';if(a.revision!==g.revision)return 'review';if(a.dependsOn.some(x=>getAction(w,x).state!=='done'))return 'blocked';if(!['confirmed','not_needed'].includes(a.support))return 'blocked';if(w.observations.some(o=>o.goalId===g.id&&o.outcome==='harm'&&o.createdAt>=a.reviewedAt))return 'review';return 'ready';}
function reason(w,a){const s=status(w,a);if(s==='done')return a.completion;if(s==='paused')return 'Goal is paused or reported achieved.';if(s==='review')return 'Goal changed or a harm observation needs review.';if(a.dependsOn.some(x=>getAction(w,x).state!=='done'))return 'A preceding action is unfinished.';if(s==='blocked')return 'Required support is '+a.support.replaceAll('_',' ')+'.';return 'Conditions recorded by you; not independently verified.';}
function updateSupport(w,actionId,p){supportFields(p);capacity(w);const a=getAction(w,actionId);insist(a.state==='todo','Completed actions are historical. Create a new action instead.');const before={support:a.support,need:a.need,provider:a.provider,supportNote:a.supportNote};Object.assign(a,{support:p.support,need:p.need,provider:p.provider,supportNote:p.supportNote});event(w,'support-updated',a.id,JSON.stringify({before,after:p}));}
function reviewAction(w,actionId,note){text(note,'Review note',true);capacity(w);const a=getAction(w,actionId);insist(a.state==='todo','Completed actions keep their original revision.');a.revision=getGoal(w,a.goalId).revision;a.reviewedAt=now();event(w,'action-reviewed',a.id,note);}
function completeAction(w,actionId,note){text(note,'Completion note',true);capacity(w);const a=getAction(w,actionId);insist(status(w,a)==='ready','Resolve support, dependencies, or review before recording completion.');a.state='done';a.completion=note;event(w,'action-completed',a.id,note);}
function observe(w,p){choice(p.outcome,OUTCOMES,'outcome');choice(p.kind,['self_reported','observed','documented'],'evidence kind');text(p.note,'Observation',true);text(p.source,'Source');if(p.kind==='documented')insist(p.source.trim(),'Documented evidence needs a source reference.');capacity(w);insist(w.observations.length<1000,'Limit: 1000 observations.');const g=getGoal(w,p.goalId);const o={id:uid('o'),goalId:g.id,revision:g.revision,outcome:p.outcome,kind:p.kind,note:p.note,source:p.source,createdAt:now()};w.observations.push(o);event(w,'observation-recorded',o.id,'Outcome is '+o.outcome+'; evidence class is '+o.kind+'.');return o;}
function metrics(w){const m={goals:w.goals.length,active:w.goals.filter(g=>g.state==='active').length,ready:0,blocked:0,review:0,paused:0,done:0,improved:w.observations.filter(o=>o.outcome==='improved').length,observations:w.observations.length,cost:0,unknownCost:0,minutes:0,unknownMinutes:0};for(const a of w.actions){m[status(w,a)]++;if(a.cost===null)m.unknownCost++;else m.cost+=a.cost;if(a.minutes===null)m.unknownMinutes++;else m.minutes+=a.minutes;}return m;}
function validate(input){
 keys(input,['schema','mode','createdAt','goals','actions','observations','events','legacy'],'Workspace');insist(input.schema===SCHEMA,'Unsupported workspace schema.');choice(input.mode,['personal','demo'],'mode');timestamp(input.createdAt);
 for(const [k,max] of [['goals',200],['actions',500],['observations',1000],['events',5000]])insist(Array.isArray(input[k])&&input[k].length<=max,'Invalid or oversized '+k+'.');
 const all=new Set();const unique=v=>{id(v);insist(!all.has(v),'Duplicate identifier.');all.add(v);};
 for(const g of input.goals){keys(g,['id','title','barrier','success','category','state','revision','createdAt','history'],'Goal');unique(g.id);goalFields(g);choice(g.state,['active','paused','achieved'],'goal state');timestamp(g.createdAt);insist(Number.isInteger(g.revision)&&g.revision>0&&Array.isArray(g.history)&&g.history.length===g.revision&&g.revision<=100,'Invalid revision history.');g.history.forEach((h,i)=>{keys(h,['revision','title','barrier','success','category','state','at'],'Revision');insist(h.revision===i+1,'Invalid revision sequence.');goalFields(h);choice(h.state,['active','paused','achieved'],'historical state');timestamp(h.at);});for(const k of ['title','barrier','success','category','state'])insist(g[k]===g.history.at(-1)[k],'Current goal differs from its revision.');}
 for(const a of input.actions){keys(a,['id','goalId','revision','title','owner','due','minutes','cost','need','provider','support','supportNote','dependsOn','state','completion','createdAt','reviewedAt'],'Action');unique(a.id);actionFields(a);const g=getGoal(input,a.goalId);insist(Number.isInteger(a.revision)&&a.revision>=1&&a.revision<=g.revision,'Invalid action revision.');choice(a.state,['todo','done'],'action state');text(a.completion,'Completion',a.state==='done');timestamp(a.createdAt);timestamp(a.reviewedAt);}
 const checked=new Set(),visiting=new Set();function visit(a){if(checked.has(a.id))return;insist(!visiting.has(a.id),'Dependency cycle.');visiting.add(a.id);for(const d of a.dependsOn){const b=getAction(input,d);insist(b.goalId===a.goalId,'Cross-goal dependency.');visit(b);}visiting.delete(a.id);checked.add(a.id);}input.actions.forEach(visit);
 for(const o of input.observations){keys(o,['id','goalId','revision','outcome','kind','note','source','createdAt'],'Observation');unique(o.id);const g=getGoal(input,o.goalId);insist(Number.isInteger(o.revision)&&o.revision>0&&o.revision<=g.revision,'Invalid evidence revision.');choice(o.outcome,OUTCOMES,'outcome');choice(o.kind,['self_reported','observed','documented'],'evidence kind');text(o.note,'Observation',true);text(o.source,'Source',o.kind==='documented');timestamp(o.createdAt);}
 const entities=new Set(all);for(const e of input.events){keys(e,['id','type','entityId','at','detail'],'History');unique(e.id);text(e.type,'Event type',true);insist(entities.has(e.entityId),'Invalid history reference.');timestamp(e.at);text(e.detail,'History detail',false,32768);}
 insist(input.legacy===null||(input.legacy&&typeof input.legacy==='object'&&!Array.isArray(input.legacy)),'Invalid retained source.');insist(new TextEncoder().encode(JSON.stringify(input)).length<=MAX_BYTES,'Workspace exceeds 2 MiB.');return clone(input);
}
function importLegacy(old){
 keys(old,['app','schemaVersion','exportedAt','draft','reviewDraft','plans','observations'],'Original journal');insist(old.app==='Dream to Action'&&old.schemaVersion==='1.0','Unsupported original schema.');timestamp(old.exportedAt);insist(Array.isArray(old.plans)&&old.plans.length<=500&&Array.isArray(old.observations)&&old.observations.length<=500,'Invalid original journal.');
 const fields=['goal','barrier','action','evidence','readiness','owner','support','helper','supportStatus','constraints','reviewDate','kind'];const checkFields=f=>{keys(f,fields,'Original fields');fields.forEach(k=>text(f[k],k));choice(f.kind,['self_reported','illustrative'],'original kind');choice(f.readiness,['unknown','ready','blocked','paused'],'original readiness');choice(f.supportStatus,SUPPORT,'original support');date(f.reviewDate);};checkFields(old.draft);keys(old.reviewDraft,['outcome','note'],'Original review draft');text(old.reviewDraft.note,'Original note');
 old.plans.forEach((p,i)=>{keys(p,['id','createdAt','fields'],'Original plan');insist(p.id==='p-'+String(i+1).padStart(4,'0'),'Invalid original plan ID.');timestamp(p.createdAt);checkFields(p.fields);});
 const known=new Set(old.plans.map(p=>p.id));old.observations.forEach(o=>{keys(o,['id','createdAt','planId','outcome','note'],'Original observation');insist(known.has(o.planId),'Invalid original plan reference.');timestamp(o.createdAt);text(o.note,'Original note',true);choice(o.outcome,['unresolved','improved','achieved','no_change','harm','changed_goal'],'original outcome');});
 const kinds=[old.draft,...old.plans.map(p=>p.fields)].map(f=>f.kind);insist(new Set(kinds).size<=1,'Mixed illustrative and personal legacy records must be separated before import. Original file is unchanged.');const w=empty(kinds[0]==='illustrative'?'demo':'personal');w.legacy=clone(old);
 const f=old.draft;if(f.goal.trim()&&f.barrier.trim()&&f.evidence.trim()){const g=addGoal(w,{title:f.goal,barrier:f.barrier,success:f.evidence,category:'Imported v0.1'});if(f.action.trim())addAction(w,{goalId:g.id,title:f.action,owner:f.owner.trim()||'Unassigned',due:f.reviewDate,minutes:null,cost:null,need:f.support,provider:f.helper,support:'unknown',supportNote:'Imported v0.1. Reconfirm current support before acting.',dependsOn:[]});if(f.readiness==='paused')reviseGoal(w,g.id,{title:g.title,barrier:g.barrier,success:g.success,category:g.category,state:'paused'},'Preserved pause from original draft.');}
 return validate(w);
}
function importData(s){text(s,'Import',true,MAX_BYTES);insist(new TextEncoder().encode(s).length<=MAX_BYTES,'Import exceeds 2 MiB.');const data=JSON.parse(s);return data.app==='Dream to Action'?importLegacy(data):validate(data);}
function csv(w){const cell=v=>{let s=String(v??'Unknown');if(/^[\s]*[=+@-]/.test(s)||/^[\t\r\n]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const rows=[['Mode','Goal','Action','Owner','Status','Due','Estimated USD','Estimated minutes','Support','Source revision']];for(const a of w.actions)rows.push([w.mode,getGoal(w,a.goalId).title,a.title,a.owner,status(w,a),a.due||'Not set',a.cost,a.minutes,a.support,a.revision]);return rows.map(r=>r.map(cell).join(',')).join('\r\n');}
return {SCHEMA,MAX_BYTES,SUPPORT,OUTCOMES,clone,empty,validate,addGoal,reviseGoal,addAction,reviseAction,updateSupport,reviewAction,completeAction,observe,status,reason,metrics,csv,importData,getGoal,getAction};
});
